### ISSUE TITLE
Image Tags in RSS break out of containers

### ISSUE THREAD

**Issue by BrianHicks** [Gizra/planet-elm#41]
There are currently some images (from Medium feeds?) that break out of the containers, at least in my browser (Chrome 55.0.2883.95 on OS X 10.11.6.)

![image](https://cloud.githubusercontent.com/assets/355401/21483384/c770eae2-cb46-11e6-981b-f4473766b992.png)

I solved this by adding a single CSS rule:

```css
.field-content img {
    max-width: 100%;
    margin-bottom: 10px;
}
```

It does this:

![image](https://cloud.githubusercontent.com/assets/355401/21483403/184766e4-cb47-11e6-8444-705712c63279.png)
